### ISSUE TITLE
Master items created delete themselves 

### ISSUE THREAD

**Issue by Tombowern** [AnalyticsEarth/AAIExpressionBuilder#8]
Hi, My master items keep deleting them self's after a few seconds....

**Comment by AnalyticsEarth** [comment]
How have you created your app? This behaviour usually has nothing to do with the extension but a characteristic if you are using the extension in a published application.

The extension should be used when developing an application in "My Work", and deleted from the sheet before publishing after you have created your master items.

Let me know if the circumstances of your issue are different from above? What happens if you create master items manually? Can you create master items manually under the same conditions? if not, this is expected behaviour.
